# Generated by Django 5.1.4 on 2024-12-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_remove_projectimage_note_remove_projectimage_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
