# Generated by Django 5.1.4 on 2024-12-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
