# Generated by Django 5.1.4 on 2024-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_remove_projectimage_completed_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='Note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='label',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnnotatdImage',
        ),
    ]
