# Generated by Django 5.1.4 on 2024-12-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_alter_projectimage_note_alter_projectimage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
